#ifndef REPLY_CODE_HPP
#define REPLY_CODE_HPP

typedef enum {
	ERR_UNKNOWNCOMMAND = 421,
	ERR_ERRONEUSNICKNAME = 432,
	ERR_NICKNAMEINUSE = 433,
	ERR_NOTREGISTERED = 451,
	ERR_NEEDMOREPARAMS = 461,
	ERR_ALREADYREGISTRED = 462
} reply_code;

#endif // REPLY_CODE_HPP
